Add fail input

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -27,6 +27,10 @@ inputs:
     description: 'Commit SHA used to search for pull request number.'
     required: false
     default: ${{ github.sha }}
+  fail:
+    description: 'Fail this action.'
+    required: false
+    default: 'false'
 runs:
   using: 'composite'
   steps:
@@ -104,3 +108,7 @@ runs:
         else
           gh api --method POST "repos/{owner}/{repo}/issues/$pr_number/comments" -f "body=$comment" --silent > /dev/null 2>&1 || raise_permission_error
         fi
+    - name: Fail this action
+      if: inputs.fail == 'true'
+      shell: bash
+      run: echo '::error::Failed due to 'fail' input specification.' && exit 1
